### PR TITLE
dummyfs: OBJECT_MODE_MEM consists of correct file type/permissions

### PR DESCRIPTION
**Pull request by niewim19**
JIRA: PD-224

## Description

Changed `OBJ_MODE_MEM` macro to consist correct file type and permissions preserving its "magic number" characteristics.
Two bytes used for file properties are set via flags, and higher two bytes are _magic number_ to distinguish whole macro used.

## Motivation and Context

 - https://github.com/phoenix-rtos/phoenix-rtos-project/issues/285

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (imxrt1064, armv7a9-zynq7000).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by damianloew** [comment]
FYI calling `exec /syspage/psh` causes system restart on imxrt106x target.

**Comment by niewim19** [comment]
> FYI calling `exec /syspage/psh` causes system restart on imxrt106x target.

For clarity - **it is good** that on imxrt1064 this change causes crash. `exec()` crashing imxrt1064 is separate issue, but this means that system interprets entries in `/syspage/` as regular files and let them execute which is aim of this PR

**Comment by niewim19** [comment]
Checked for zynq target, it works:
image

**Review by agkaminski — APPROVED** [review]
Neat fix

**Review by HBuczynski — APPROVED** [review]

**Comment by nalajcie** [comment]
FYI, try to use github commit keywords for linking / closing github issues (see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

If You would write:
```
Fixes phoenix-rtos/phoenix-rtos-project#285
```

inside the commit message, the PR would be linked to the issue and - upon merge - the issue would be automatically closed.

(please note that the commit keywords work only when PR is onto the default branch (master))

**Pull request merged**
